# -*- coding: utf-8 -*-
"""Web Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mOPkAOMVi2wXpFdTCec5gDKnVyd2lDdE
"""

#interactive python notebook

#none= cpu, Gpu=graphuical processing unit,TPU=Tensor processing unit can be found in runtime --> change runtime type

#pandas is a package to analyse tabular data

!pip install requests

from bs4 import BeautifulSoup  #to scrap/retrieve the data from websites
import requests

url = 'https://www.flipkart.com/search?q=mobiles&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off'
page = requests.get(url)

page.text

soup = BeautifulSoup(page.text,'html.parser')

soup.title

name=[]
price=[]
rating=[]  #To get these links from url
for i in soup.findAll('a',href=True,attrs={'class':'_31qSD5'}): #the a in findall is the html <a> tag.It refers to that attribute.
  ni=i.find('div',attrs={'class':'_3wU53n'})
  pi=i.find('div',attrs={'class':'_1vC4OE _2rQ-NK'})
  ri=i.find('div',attrs={'class':'hGSR34'})
  name.append(ni.text)
  price.append(pi.text)  #without using .text it directly gives the code. we use text method to ensure that we get the text specifically.
  rating.append(ri.text)

name

price

rating

import pandas as pd

df=pd.DataFrame(list(zip(name,price,rating)))  #Combine the name price and rating using the zip and list.Dataframe is used for tabular format.
df.columns=['Name','Price','Rating']

df

#If we dont find developer APIs then we should use Web Scraping.

#Try going for the next page scraping as well.